sudo: false
 
language: node_js
node_js:
  - "6"
 
before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
 
branches:
  only:
    - eslint
 
before_script:
  - meteor npm install
 
script:
  - meteor npm run lint